export const translations = {
    en: {
        title: "CSS Processor",
        description: "Transform your CSS with unique IDs and custom replacements",
        howToUse: "How to use:",
        useDefineUid: "Use #define word __UID__ to define any word as a unique short ID",
        useDefineReplacement: "Use #define word replacement for custom replacements",
        classNameReplacements: "Class name replacements only affect class=\"...\" in HTML nodes",
        unusedCssRules: "Unused CSS rules are automatically removed",
        uidDetails: "UIDs contain letters and digits, but always start with a letter",
        inputLabel: "Input CSS and HTML:",
        process: "Process CSS",
        processAria: "Process the CSS input",
        copy: "Copy Output",
        copyAria: "Copy the output",
        copyStatus: "Copied to clipboard!",
        outputLabel: "Processed Output:"
    },
    es: {
        title: "Procesador de CSS",
        description: "Transforma tu CSS con IDs únicos y reemplazos personalizados",
        howToUse: "Cómo usar:",
        useDefineUid: "Usa #define palabra __UID__ para definir cualquier palabra como un ID corto único",
        useDefineReplacement: "Usa #define palabra reemplazo para reemplazos personalizados",
        classNameReplacements: "Los reemplazos de nombres de clase solo afectan a class=\"...\" en nodos HTML",
        unusedCssRules: "Las reglas CSS no utilizadas se eliminan automáticamente",
        uidDetails: "Los UIDs contienen letras y dígitos, pero siempre comienzan con una letra",
        inputLabel: "Entrada CSS y HTML:",
        process: "Procesar CSS",
        processAria: "Procesar la entrada CSS",
        copy: "Copiar Salida",
        copyAria: "Copiar la salida",
        copyStatus: "¡Copiado al portapapeles!",
        outputLabel: "Salida Procesada:"
    },
    zh: {
        title: "CSS处理器",
        description: "使用唯一ID和自定义替换转换您的CSS",
        howToUse: "如何使用：",
        useDefineUid: "使用 #define 单词 __UID__ 将任何单词定义为唯一的短ID",
        useDefineReplacement: "使用 #define 单词 替换内容 进行自定义替换",
        classNameReplacements: "类名替换仅影响HTML节点中的class=\"...\"",
        unusedCssRules: "未使用的CSS规则将自动删除",
        uidDetails: "UID包含字母和数字，但始终以字母开头",
        inputLabel: "输入CSS和HTML：",
        process: "处理CSS",
        processAria: "处理CSS输入",
        copy: "复制输出",
        copyAria: "复制输出内容",
        copyStatus: "已复制到剪贴板！",
        outputLabel: "处理后的输出："
    },
    hi: {
        title: "सीएसएस प्रोसेसर",
        description: "अद्वितीय आईडी और कस्टम प्रतिस्थापन के साथ अपने सीएसएस को बदलें",
        howToUse: "उपयोग कैसे करें:",
        useDefineUid: "#define शब्द __UID__ का उपयोग करके किसी भी शब्द को एक अद्वितीय छोटा आईडी बनाएं",
        useDefineReplacement: "#define शब्द प्रतिस्थापन का उपयोग करके कस्टम प्रतिस्थापन करें",
        classNameReplacements: "क्लास नाम प्रतिस्थापन केवल HTML नोड्स में class=\"...\" को प्रभावित करते हैं",
        unusedCssRules: "अप्रयुक्त CSS नियम स्वचालित रूप से हटा दिए जाते हैं",
        uidDetails: "UID में अक्षर और अंक शामिल होते हैं, लेकिन हमेशा एक अक्षर से शुरू होते हैं",
        inputLabel: "CSS और HTML इनपुट करें:",
        process: "CSS प्रोसेस करें",
        processAria: "CSS इनपुट प्रोसेस करें",
        copy: "आउटपुट कॉपी करें",
        copyAria: "आउटपुट कॉपी करें",
        copyStatus: "क्लिपबोर्ड पर कॉपी किया गया!",
        outputLabel: "प्रोसेस्ड आउटपुट:"
    },
    ar: {
        title: "معالج CSS",
        description: "حوّل CSS الخاص بك بمعرفات فريدة واستبدالات مخصصة",
        howToUse: "كيفية الاستخدام:",
        useDefineUid: "استخدم #define كلمة __UID__ لتعريف أي كلمة كمعرف قصير فريد",
        useDefineReplacement: "استخدم #define كلمة استبدال لإجراء استبدالات مخصصة",
        classNameReplacements: "استبدالات أسماء الفئات تؤثر فقط على class=\"...\" في عقد HTML",
        unusedCssRules: "يتم إزالة قواعد CSS غير المستخدمة تلقائيًا",
        uidDetails: "تحتوي المعرفات الفريدة على حروف وأرقام، ولكنها تبدأ دائمًا بحرف",
        inputLabel: "إدخال CSS وHTML:",
        process: "معالجة CSS",
        processAria: "معالجة إدخال CSS",
        copy: "نسخ الإخراج",
        copyAria: "نسخ الإخراج",
        copyStatus: "تم النسخ إلى الحافظة!",
        outputLabel: "الإخراج المعالج:"
    },
    pt: {
        title: "Processador de CSS",
        description: "Transforme seu CSS com IDs únicos e substituições personalizadas",
        howToUse: "Como usar:",
        useDefineUid: "Use #define palavra __UID__ para definir qualquer palavra como um ID curto único",
        useDefineReplacement: "Use #define palavra substituição para substituições personalizadas",
        classNameReplacements: "Substituições de nomes de classe afetam apenas class=\"...\" em nós HTML",
        unusedCssRules: "Regras CSS não utilizadas são removidas automaticamente",
        uidDetails: "Os UIDs contêm letras e dígitos, mas sempre começam com uma letra",
        inputLabel: "Entrada CSS e HTML:",
        process: "Processar CSS",
        processAria: "Processar a entrada CSS",
        copy: "Copiar Saída",
        copyAria: "Copiar a saída",
        copyStatus: "Copiado para a área de transferência!",
        outputLabel: "Saída Processada:"
    },
    bn: {
        title: "সিএসএস প্রসেসর",
        description: "অনন্য আইডি এবং কাস্টম প্রতিস্থাপন দিয়ে আপনার সিএসএস রূপান্তর করুন",
        howToUse: "কীভাবে ব্যবহার করবেন:",
        useDefineUid: "#define শব্দ __UID__ ব্যবহার করে যেকোনো শব্দকে একটি অনন্য সংক্ষিপ্ত আইডি হিসেবে সংজ্ঞায়িত করুন",
        useDefineReplacement: "#define শব্দ প্রতিস্থাপন ব্যবহার করে কাস্টম প্রতিস্থাপন করুন",
        classNameReplacements: "ক্লাস নাম প্রতিস্থাপন শুধুমাত্র HTML নোডে class=\"...\"-কে প্রভাবিত করে",
        unusedCssRules: "অব্যবহৃত CSS নিয়ম স্বয়ংক্রিয়ভাবে মুছে ফেলা হয়",
        uidDetails: "UID-তে অক্ষর এবং সংখ্যা থাকে, তবে সবসময় একটি অক্ষর দিয়ে শুরু হয়",
        inputLabel: "CSS এবং HTML ইনপুট:",
        process: "CSS প্রক্রিয়া করুন",
        processAria: "CSS ইনপুট প্রক্রিয়া করুন",
        copy: "আউটপুট কপি করুন",
        copyAria: "আউটপুট কপি করুন",
        copyStatus: "ক্লিপবোর্ডে কপি করা হয়েছে!",
        outputLabel: "প্রক্রিয়াজাত আউটপুট:"
    },
    ru: {
        title: "Процессор CSS",
        description: "Преобразуйте CSS с уникальными ID и пользовательскими заменами",
        howToUse: "Как использовать:",
        useDefineUid: "Используйте #define слово __UID__ для определения любого слова как уникальный короткий ID",
        useDefineReplacement: "Используйте #define слово замена для пользовательских замен",
        classNameReplacements: "Замены имен классов влияют только на class=\"...\" в узлах HTML",
        unusedCssRules: "Неиспользуемые правила CSS автоматически удаляются",
        uidDetails: "UID содержат буквы и цифры, но всегда начинаются с буквы",
        inputLabel: "Ввод CSS и HTML:",
        process: "Обработать CSS",
        processAria: "Обработать ввод CSS",
        copy: "Копировать вывод",
        copyAria: "Копировать вывод",
        copyStatus: "Скопировано в буфер обмена!",
        outputLabel: "Обработанный вывод:"
    },
    ja: {
        title: "CSSプロセッサ",
        description: "ユニークなIDとカスタム置換でCSSを変換",
        howToUse: "使用方法：",
        useDefineUid: "#define 単語 __UID__ を使って任意の単語をユニークな短いIDとして定義",
        useDefineReplacement: "#define 単語 置換 を使ってカスタム置換を行う",
        classNameReplacements: "クラス名の置換はHTMLノードのclass=\"...\"にのみ影響",
        unusedCssRules: "未使用のCSSルールは自動的に削除されます",
        uidDetails: "UIDは文字と数字を含み、常に文字で始まります",
        inputLabel: "CSSとHTMLの入力：",
        process: "CSSを処理",
        processAria: "CSS入力を処理",
        copy: "出力をコピー",
        copyAria: "出力をコピー",
        copyStatus: "クリップボードにコピーしました！",
        outputLabel: "処理済み出力："
    },
    pa: {
        title: "ਸੀਐਸਐਸ ਪ੍ਰੋਸੈਸਰ",
        description: "ਵਿਲੱਖਣ ਆਈਡੀ ਅਤੇ ਕਸਟਮ ਬਦਲਾਵਾਂ ਨਾਲ ਆਪਣੇ ਸੀਐਸਐਸ ਨੂੰ ਬਦਲੋ",
        howToUse: "ਵਰਤੋਂ ਕਿਵੇਂ ਕਰੀਏ:",
        useDefineUid: "ਕਿਸੇ ਵੀ ਸ਼ਬਦ ਨੂੰ ਵਿਲੱਖਣ ਛੋਟੀ ਆਈਡੀ ਵਜੋਂ ਪਰਿਭਾਸ਼ਿਤ ਕਰਨ ਲਈ #define ਸ਼ਬਦ __UID__ ਵਰਤੋ",
        useDefineReplacement: "ਕਸਟਮ ਬਦਲਾਵਾਂ ਲਈ #define ਸ਼ਬਦ ਬਦਲਾਓ ਵਰਤੋ",
        classNameReplacements: "ਕਲਾਸ ਨਾਮ ਬਦਲਾਅ ਸਿਰਫ HTML ਨੋਡਜ਼ ਵਿੱਚ class=\"...\" ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਦੇ ਹਨ",
        unusedCssRules: "ਅਣਵਰਤੇ CSS ਨਿਯਮ ਆਪਣੇ ਆਪ ਹਟਾਏ ਜਾਂਦੇ ਹਨ",
        uidDetails: "UID ਵਿੱਚ ਅੱਖਰ ਅਤੇ ਅੰਕ ਸ਼ਾਮਲ ਹੁੰਦੇ ਹਨ, ਪਰ ਹਮੇਸ਼ਾ ਇੱਕ ਅੱਖਰ ਨਾਲ ਸ਼ੁਰੂ ਹੁੰਦੇ ਹਨ",
        inputLabel: "CSS ਅਤੇ HTML ਇੰਪੁੱਟ:",
        process: "CSS ਪ੍ਰੋਸੈਸ ਕਰੋ",
        processAria: "CSS ਇੰਪੁੱਟ ਪ੍ਰੋਸੈਸ ਕਰੋ",
        copy: "ਆਉਟਪੁੱਟ ਕਾਪੀ ਕਰੋ",
        copyAria: "ਆਉਟਪੁੱਟ ਕਾਪੀ ਕਰੋ",
        copyStatus: "ਕਲਿੱਪਬੋਰਡ ਵਿੱਚ ਕਾਪੀ ਕੀਤਾ ਗਿਆ!",
        outputLabel: "ਪ੍ਰੋਸੈਸਡ ਆਉਟਪੁੱਟ:"
    },
    de: {
        title: "CSS-Prozessor",
        description: "Transformieren Sie Ihr CSS mit eindeutigen IDs und benutzerdefinierten Ersetzungen",
        howToUse: "So verwenden Sie:",
        useDefineUid: "Verwenden Sie #define Wort __UID__, um ein beliebiges Wort als eindeutige kurze ID zu definieren",
        useDefineReplacement: "Verwenden Sie #define Wort Ersatz für benutzerdefinierte Ersetzungen",
        classNameReplacements: "Klassennamen-Ersetzungen wirken sich nur auf class=\"...\" in HTML-Knoten aus",
        unusedCssRules: "Unbenutzte CSS-Regeln werden automatisch entfernt",
        uidDetails: "UIDs enthalten Buchstaben und Ziffern, beginnen aber immer mit einem Buchstaben",
        inputLabel: "CSS- und HTML-Eingabe:",
        process: "CSS verarbeiten",
        processAria: "CSS-Eingabe verarbeiten",
        copy: "Ausgabe kopieren",
        copyAria: "Ausgabe kopieren",
        copyStatus: "In die Zwischenablage kopiert!",
        outputLabel: "Verarbeitete Ausgabe:"
    },
    jv: {
        title: "Prosesor CSS",
        description: "Ngowahi CSS nganggo ID unik lan panggantos khusus",
        howToUse: "Carane nggunakake:",
        useDefineUid: "Gunakake #define tembung __UID__ kanggo nemtokake tembung apa wae minangka ID cendhak unik",
        useDefineReplacement: "Gunakake #define tembung panggantos kanggo panggantos khusus",
        classNameReplacements: "Panggantos jeneng kelas mung mengaruhi class=\"...\" ing nod HTML",
        unusedCssRules: "Aturan CSS sing ora digunakake bakal otomatis dibusak",
        uidDetails: "UID ngemot huruf lan angka, nanging tansah diwiwiti karo huruf",
        inputLabel: "Input CSS lan HTML:",
        process: "Proses CSS",
        processAria: "Proses input CSS",
        copy: "Salin Output",
        copyAria: "Salin output",
        copyStatus: "Disalin menyang clipboard!",
        outputLabel: "Output sing diproses:"
    },
    wuu: {
        title: "CSS处理器",
        description: "用独特ID同自定义替换转换侬个CSS",
        howToUse: "哪能用：",
        useDefineUid: "用 #define 单词 __UID__ 把任何单词定义成一个独特个短ID",
        useDefineReplacement: "用 #define 单词 替换内容 来做自定义替换",
        classNameReplacements: "类名替换只影响HTML节点里个class=\"...\"",
        unusedCssRules: "勿用个CSS规则会自动删掉",
        uidDetails: "UID包括字母同数字，但总归要从字母开始",
        inputLabel: "输入CSS同HTML：",
        process: "处理CSS",
        processAria: "处理CSS输入",
        copy: "复制输出",
        copyAria: "复制输出内容",
        copyStatus: "已经复制到剪贴板！",
        outputLabel: "处理好个输出："
    },
    ms: {
        title: "Pemproses CSS",
        description: "Ubah CSS anda dengan ID unik dan penggantian tersuai",
        howToUse: "Cara menggunakan:",
        useDefineUid: "Gunakan #define perkataan __UID__ untuk mentakrifkan mana-mana perkataan sebagai ID pendek unik",
        useDefineReplacement: "Gunakan #define perkataan penggantian untuk penggantian tersuai",
        classNameReplacements: "Penggantian nama kelas hanya mempengaruhi class=\"...\" dalam nod HTML",
        unusedCssRules: "Peraturan CSS yang tidak digunakan akan dipadam secara automatik",
        uidDetails: "UID mengandungi huruf dan digit, tetapi sentiasa bermula dengan huruf",
        inputLabel: "Input CSS dan HTML:",
        process: "Proses CSS",
        processAria: "Proses input CSS",
        copy: "Salin Output",
        copyAria: "Salin output",
        copyStatus: "Disalin ke papan klip!",
        outputLabel: "Output Diproses:"
    },
    te: {
        title: "సీఎస్ఎస్ ప్రాసెసర్",
        description: "విశిష్ట ఐడీలు మరియు కస్టమ్ రీప్లేస్‌మెంట్‌లతో మీ సీఎస్ఎస్‌ను మార్చండి",
        howToUse: "ఎలా ఉపయోగించాలి:",
        useDefineUid: "ఏదైనా పదాన్ని విశిష్ట షార్ట్ ఐడీగా నిర్వచించడానికి #define పదం __UID__ ఉపయోగించండి",
        useDefineReplacement: "కస్టమ్ రీప్లేస్‌మెంట్‌ల కోసం #define పదం రీప్లేస్‌మెంట్ ఉపయోగించండి",
        classNameReplacements: "క్లాస్ నేమ్ రీప్లేస్‌మెంట్‌లు HTML నోడ్స్‌లో class=\"...\"ను మాత్రమే ప్రభావితం చేస్తాయి",
        unusedCssRules: "ఉపయోగించని CSS నియమాలు స్వయంచాలకంగా తొలగించబడతాయి",
        uidDetails: "UIDలు అక్షరాలు మరియు అంకెలను కలిగి ఉంటాయి, కానీ ఎల్లప్పుడూ అక్షరంతో ప్రారంభమవుతాయి",
        inputLabel: "CSS మరియు HTML ఇన్‌పుట్:",
        process: "CSS ప్రాసెస్ చేయండి",
        processAria: "CSS ఇన్‌పుట్ ప్రాసెస్ చేయండి",
        copy: "అవుట్‌పుట్ కాపీ చేయండి",
        copyAria: "అవుట్‌పుట్ కాపీ చేయండి",
        copyStatus: "క్లిప్‌బోర్డ్‌కు కాపీ చేయబడింది!",
        outputLabel: "ప్రాసెస్ చేయబడిన అవుట్‌పుట్:"
    },
    vi: {
        title: "Bộ xử lý CSS",
        description: "Chuyển đổi CSS của bạn với các ID duy nhất và thay thế tùy chỉnh",
        howToUse: "Cách sử dụng:",
        useDefineUid: "Sử dụng #define từ __UID__ để định nghĩa bất kỳ từ nào thành một ID ngắn duy nhất",
        useDefineReplacement: "Sử dụng #define từ thay_thế để thực hiện thay thế tùy chỉnh",
        classNameReplacements: "Thay thế tên lớp chỉ ảnh hưởng đến class=\"...\" trong các nút HTML",
        unusedCssRules: "Các quy tắc CSS không được sử dụng sẽ tự động bị xóa",
        uidDetails: "UID chứa các chữ cái và số, nhưng luôn bắt đầu bằng một chữ cái",
        inputLabel: "Nhập CSS và HTML:",
        process: "Xử lý CSS",
        processAria: "Xử lý đầu vào CSS",
        copy: "Sao chép đầu ra",
        copyAria: "Sao chép đầu ra",
        copyStatus: "Đã sao chép vào bộ nhớ tạm!",
        outputLabel: "Đầu ra đã xử lý:"
    },
    ko: {
        title: "CSS 프로세서",
        description: "고유 ID와 사용자 지정 교체로 CSS를 변환",
        howToUse: "사용 방법:",
        useDefineUid: "#define 단어 __UID__를 사용하여 임의의 단어를 고유한 짧은 ID로 정의",
        useDefineReplacement: "#define 단어 교체를 사용하여 사용자 지정 교체 수행",
        classNameReplacements: "클래스 이름 교체는 HTML 노드의 class=\"...\"에만 영향을 미침",
        unusedCssRules: "사용되지 않은 CSS 규칙은 자동으로 제거됨",
        uidDetails: "UID는 문자와 숫자를 포함하며, 항상 문자로 시작",
        inputLabel: "CSS 및 HTML 입력:",
        process: "CSS 처리",
        processAria: "CSS 입력 처리",
        copy: "출력 복사",
        copyAria: "출력 복사",
        copyStatus: "클립보드에 복사됨!",
        outputLabel: "처리된 출력:"
    },
    fr: {
        title: "Processeur CSS",
        description: "Transformez votre CSS avec des ID uniques et des remplacements personnalisés",
        howToUse: "Comment utiliser :",
        useDefineUid: "Utilisez #define mot __UID__ pour définir n'importe quel mot comme un ID court unique",
        useDefineReplacement: "Utilisez #define mot remplacement pour des remplacements personnalisés",
        classNameReplacements: "Les remplacements de noms de classe affectent uniquement class=\"...\" dans les nœuds HTML",
        unusedCssRules: "Les règles CSS inutilisées sont automatiquement supprimées",
        uidDetails: "Les UID contiennent des lettres et des chiffres, mais commencent toujours par une lettre",
        inputLabel: "Entrée CSS et HTML :",
        process: "Traiter le CSS",
        processAria: "Traiter l'entrée CSS",
        copy: "Copier la sortie",
        copyAria: "Copier la sortie",
        copyStatus: "Copié dans le presse-papiers !",
        outputLabel: "Sortie traitée :"
    },
    mr: {
        title: "सीएसएस प्रोसेसर",
        description: "अद्वितीय आयडी आणि सानुकूल बदलांसह आपले सीएसएस रूपांतरित करा",
        howToUse: "कसे वापरावे:",
        useDefineUid: "कोणत्याही शब्दाला अद्वितीय छोटा आयडी म्हणून परिभाषित करण्यासाठी #define शब्द __UID__ वापरा",
        useDefineReplacement: "सानुकूल बदलांसाठी #define शब्द बदल वापरा",
        classNameReplacements: "वर्ग नाव बदल फक्त HTML नोड्समधील class=\"...\" वर परिणाम करतात",
        unusedCssRules: "न वापरलेले CSS नियम स्वयंचलितपणे काढले जातात",
        uidDetails: "UID मध्ये अक्षरे आणि अंक असतात, परंतु नेहमी अक्षराने सुरू होतात",
        inputLabel: "CSS आणि HTML इनपुट:",
        process: "CSS प्रक्रिया करा",
        processAria: "CSS इनपुट प्रक्रिया करा",
        copy: "आउटपुट कॉपी करा",
        copyAria: "आउटपुट कॉपी करा",
        copyStatus: "क्लिपबोर्डवर कॉपी केले!",
        outputLabel: "प्रक्रिया केलेले आउटपुट:"
    },
    ta: {
        title: "சிஎஸ்எஸ் புரோசெசர்",
        description: "தனித்துவமான ஐடிகள் மற்றும் தனிப்பயன் மாற்றங்களுடன் உங்கள் சிஎஸ்எஸ்ஐ மாற்றவும்",
        howToUse: "எப்படி பயன்படுத்துவது:",
        useDefineUid: "எந்த வார்த்தையையும் தனித்துவமான குறுகிய ஐடியாக வரையறுக்க #define வார்த்தை __UID__ பயன்படுத்தவும்",
        useDefineReplacement: "தனிப்பயன் மாற்றங்களுக்கு #define வார்த்தை மாற்றம் பயன்படுத்தவும்",
        classNameReplacements: "வகுப்பு பெயர் மாற்றங்கள் HTML நோட்களில் class=\"...\" மட்டுமே பாதிக்கும்",
        unusedCssRules: "பயன்படுத்தப்படாத CSS விதிகள் தானாக நீக்கப்படும்",
        uidDetails: "UIDகள் எழுத்துக்கள் மற்றும் இலக்கங்களை உள்ளடக்கியவை, ஆனால் எப்போதும் ஒரு எழுத்துடன் தொடங்கும்",
        inputLabel: "CSS மற்றும் HTML உள்ளீடு:",
        process: "CSS ஐ செயலாக்கு",
        processAria: "CSS உள்ளீட்டை செயலாக்கு",
        copy: "வெளியீட்டை நகலெடு",
        copyAria: "வெளியீட்டை நகலெடு",
        copyStatus: "கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது!",
        outputLabel: "செயலாக்கப்பட்ட வெளியீடு:"
    }
};

export function setLanguage(lang) {
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    document.querySelectorAll('[data-i18n-aria]').forEach(element => {
        const key = element.getAttribute('data-i18n-aria');
        if (translations[lang][key]) {
            element.setAttribute('aria-label', translations[lang][key]);
        }
    });
}
